import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

// self.__WB_MANIFEST is injected by Vite/Workbox during build
declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache API requests (customize the pattern as needed)
registerRoute(
  ({ url }) => url.pathname.startsWith("/api/"),
  new StaleWhileRevalidate({
    cacheName: "api-cache",
  }),
);

// Cache static assets (images, fonts, etc)
registerRoute(
  ({ request }) => request.destination === "image" || request.destination === "font",
  new StaleWhileRevalidate({
    cacheName: "assets-cache",
  }),
);
